# Generated by Django 3.2.7 on 2021-09-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Found_Item_name', models.CharField(max_length=20)),
                ('Found_Item_img', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
