# Generated by Django 3.2.7 on 2021-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='date',
            field=models.DateField(),
        ),
    ]
