# Generated by Django 3.2.7 on 2021-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_founditems_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='Found_Item_img',
            field=models.ImageField(default='', upload_to='items/image'),
        ),
    ]
