# Generated by Django 3.2.7 on 2021-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_founditems_found_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('ph', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('states', models.CharField(max_length=40)),
                ('zip', models.IntegerField(max_length=5)),
                ('obj_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
