# Generated by Django 3.2.7 on 2021-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_claimperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimperson',
            name='ph',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claimperson',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
