# Generated by Django 3.2.7 on 2021-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20210918_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimperson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='claimperson',
            name='obj_name',
        ),
        migrations.AddField(
            model_name='claimperson',
            name='claim_reason',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
